services:
  maildev:
    image: maildev/maildev:latest
    container_name: maildev
    ports:
      - "1080:1080" # UI
    restart: unless-stopped
    networks:
      - garmin-persistent-livetrack-network

  postgres:
    ports:
      - 5432:5432

  migrate:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres # faster but less safe startup
    command: ["yarn", "db:push"]

  ui:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    env_file:
      - ./ui/.env.dev
    volumes:
      - ./ui:/app
      - /app/node_modules
