FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json pnpm*.yaml ./

RUN npm i -g pnpm
RUN pnpm install

FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=builder /app/node_modules/ /app/node_modules/

ENV NODE_ENV=development

CMD ["yarn", "dev", "--host", "0.0.0.0"]
